name: Deeploy code
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ap-south-1
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Create build
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
  upload-build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build Artifact
        uses: actions/download-artifact@v4
        with: 
          name: dist
      - name: Show Build files
        run: ls
      - name: Create zip
        run: zip -r dist.zip ./* 
      - name: Show post zip files
        run: ls
      - name: Upload to S3 Bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}
        run: |
          aws s3 cp dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/dist --recursive
      - name: Upload Artifact
        run: echo "Upload Artifact to ${{secrets.AWS_S3_BUCKET_NAME}}"

